language: node_js
services:
  - rabbitmq
node_js:
  - "4"
sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
