language: node_js
node_js:
  - "8"
sudo: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2501 1000 &
deploy:
  skip_cleanup: true
  provider: npm
  email: info@molecuel.org
  api_key: $NPM_TOKEN
  on:
    repo: molecuel/mlcl_mailer
    branch: master